### ISSUE TITLE
Touch Dig Doubles everything when any other mod is installed[ArsMagica2_1.5.0-9]

### ISSUE THREAD

**Issue by emeralis00** [Growlith1223/ArsMagica2#42]
Using the simple spell:
Group: Touch
Grammar: Dig

I'm able to double every block I mine using the spell. The effect is not limited to ores, but applies to every block broken by the spell (provided it drops something), and therefore get infinite ore. No idea what in particular is causing it, but its accompanied by some console spam.
https://i.imgur.com/tjQvDHq.png

EDIT: this is actually an interaction between Ars Magica and some other mod. I'm going to check see which.

**Comment by emeralis00** [comment]
Correction, it appears to occur if Ars Magica is installed with another mod. The other mod doesn't seem to matter.
Tested individually with:
Realistic Terrain Generation
Immersive Engineering
Mantle

This makes it unfeasable to include Ars Magica in a pack, since even a single library mod results in doubling everything.

**Comment by Growlith1223** [comment]
not going to lie, i was kind of expecting a bug with the dig component after my fix lol, the way i fixed feather touch was very derpy and just overall bad... lol thanks for telling me!

**Comment by Growlith1223** [comment]
also regarding that cosnole spam, that was something i put in to see why npcs weren't able cast spells but never removed it lol, will be removed in a bit!

**Comment by emeralis00** [comment]
I'm going to try to find the most minimalistic mod ever and see if still happens with Ars Magica.

**Comment by emeralis00** [comment]
Okay, using Forge version 2125, Ars Magica 2 version 1.5.0-9, I was able to get the doubling bug _without_ any other mod installed. Though not having another mod installed seems to make it only happen sometimes.

**Comment by Zieg777** [comment]
Odd that it would do that with only touch. I generally only use projectile, so I never noticed this.

**Comment by Growlith1223** [comment]
alright, did a proper fix, and just tested with touch + dig and now im not getting this bug. this is also with Immersive engineering and forge latest being in.

**Comment by PokeMaserJ** [comment]
So it seems Projectile Dig now doubles any block that has been "mined" on 1.5.0-9. It's late for me, so I'll test later. A note, this behavior didn't seem to happen 1.5.0-6

**Comment by Growlith1223** [comment]
already known, the fix is already in, just haven't done a release yet

**Comment by emeralis00** [comment]
Fixed in version 1.5.0-10

**Comment by Zieg777** [comment]
I'm assuming that the projectile silk touch dig not dropping anything from certain ores (redstone) and changing blocks based off ore dictionary is in here as well?

**Comment by Growlith1223** [comment]
correct, Zieg, instead of calling BreakBlock, im calling HarvestBlock, which HarvestBlock not only calls BreakBlock but also calls more things

**Comment by Zieg777** [comment]
Ah ok. I've not tested it yet since I've got a fortune 3 pick anyway, but does fortune/prosperity get called correctly?
